/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface UiDropdown {
      'icon': 'caret' | 'angle';
      'label': string;
      'toggleDropdown': () => void;
    }
  }

  interface HTMLUiDropdownElement extends StencilComponents.UiDropdown, HTMLStencilElement {}

  var HTMLUiDropdownElement: {
    prototype: HTMLUiDropdownElement;
    new (): HTMLUiDropdownElement;
  };
  interface HTMLElementTagNameMap {
    'ui-dropdown': HTMLUiDropdownElement;
  }
  interface ElementTagNameMap {
    'ui-dropdown': HTMLUiDropdownElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ui-dropdown': JSXElements.UiDropdownAttributes;
    }
  }
  namespace JSXElements {
    export interface UiDropdownAttributes extends HTMLAttributes {
      'icon'?: 'caret' | 'angle';
      'label'?: string;
      'onOnClick'?: (event: CustomEvent) => void;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;